parameters:
    ixarlie_mutex.flock_store.class: Symfony\Component\Lock\Store\FlockStore
    ixarlie_mutex.memcached_store.class: Symfony\Component\Lock\Store\MemcachedStore
    ixarlie_mutex.redis_store.class: Symfony\Component\Lock\Store\RedisStore
