# yamllint disable rule:line-length
# yamllint disable rule:braces

name: CI

on:
    pull_request:
    push:
        branches:
            - "master"

jobs:
    phpunit:
        name: "PHPUnit"
        runs-on: "ubuntu-20.04"

        strategy:
            fail-fast: false
            matrix:
                experimental: [ false ]
                composer-options: [ "--prefer-stable" ]
                php-version:
                    - "8.1"
                    - "8.2"
                dependencies:
                    - "highest"
                symfony-require:
                    - "5.4.*"
                    - "^6.0"

        steps:
            - name: "Checkout"
              uses: "actions/checkout@v2"
              with:
                  fetch-depth: 2

            - name: "Install PHP"
              uses: "shivammathur/setup-php@v2"
              with:
                  php-version: "${{ matrix.php-version }}"
                  coverage: "xdebug"
                  ini-values: "zend.assertions=1"
                  tools: "flex"

            - name: "Install dependencies with Composer"
              uses: "ramsey/composer-install@v1"
              env:
                  SYMFONY_REQUIRE: "${{ matrix.symfony-require }}"
              with:
                  dependency-versions: "${{ matrix.dependencies }}"
                  composer-options: "${{ matrix.composer-options }}"

            - name: "Run PHPUnit"
              run: "vendor/bin/phpunit"
